[package]
name = "inc-bin"
version = "0.1.0"
authors = ["Ethan Hall <ethan@ehdev.io>"]

[dependencies]
inc-core = { version = "0.1.0", path = "../../lib/core" }
docopt = "0.8.1"
serde = "1.0"
serde_derive = "1.0"
log = "0.3"

[dev-dependencies]
assert_cli = "0.5"

[[bin]]
name = "inc"
test = false
doc = false